# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ba36d54807c0fe31022f2ec197f991a71c33db5d1a60419f15376c427b1d2edcb406821540066d93a706dbd8e6bcb25fc64599b9be05404432b577f4dcc060e0

test:
  secret_key_base: ee7805dcb5df4f1d5804c1b14a5239c958eb0728bc4813a72970508336b9b813277ff62b3e687f4e91834707346316f8c01be561072dd83de5630a5101c2bea6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
